In [39]:
#!pip install wandb==0.16.3
#!pip install ydata-profiling==4.13.0 
#!pip install pandas==2.2.0

# Outdated dependencies with Python 3.13.

!pip install wandb==0.22.0
!pip install ydata-profiling>=4.17,<5
!pip install pandas==2.3.2

Requirement already satisfied: wandb==0.22.0 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (0.22.0)
Requirement already satisfied: click>=8.0.1 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from wandb==0.22.0) (8.3.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from wandb==0.22.0) (3.1.45)
Requirement already satisfied: packaging in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from wandb==0.22.0) (25.0)
Requirement already satisfied: platformdirs in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from wandb==0.22.0) (4.5.0)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from wandb==0.22.0) (6.33.0)
Requirement already satisfied: pydantic<3 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from wandb==0.22.0) (2.12.3)
Requirement already satisfied: pyyaml in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from wandb==0.22.0) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from wandb==0.22.0) (2.32.5)
Requirement already satisfied: sentry-sdk>=2.0.0 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from wandb==0.22.0) (2.42.1)
Requirement already satisfied: typing-extensions<5,>=4.8 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from wandb==0.22.0) (4.15.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from gitpython!=3.1.29,>=1.0.0->wandb==0.22.0) (4.0.12)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from pydantic<3->wandb==0.22.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from pydantic<3->wandb==0.22.0) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from pydantic<3->wandb==0.22.0) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from requests<3,>=2.0.0->wandb==0.22.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from requests<3,>=2.0.0->wandb==0.22.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from requests<3,>=2.0.0->wandb==0.22.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from requests<3,>=2.0.0->wandb==0.22.0) (2025.10.5)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb==0.22.0) (5.0.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
/bin/bash: line 1: 5: No such file or directory
Requirement already satisfied: pandas==2.3.2 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from pandas==2.3.2) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from pandas==2.3.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from pandas==2.3.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from pandas==2.3.2) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/miniconda/envs/mlops-dev-course/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas==2.3.2) (1.17.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

1. Fetch the artifact we just created (sample.csv) from W&B and read it with pandas:

In [40]:
import wandb
import pandas as pd
# Note that we use save_code=True in the call to wandb.init so the notebook is uploaded and versioned by W&B
run = wandb.init(project="nyc_airbnb", group="eda", save_code=True)
local_path = wandb.use_artifact("sample.csv:latest").file()
df = pd.read_csv(local_path)

2. Explore the data in df

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20000 non-null  int64
 1   name                            19993 non-null  object
 2   host_id                         20000 non-null  int64
 3   host_name                       19992 non-null  object
 4   neighbourhood_group             20000 non-null  object
 5   neighbourhood                   20000 non-null  object
 6   latitude                        20000 non-null  float64
 7   longitude                       20000 non-null  float64
 8   room_type                       20000 non-null  object
 9   price                           20000 non-null  int64
 10  minimum_nights                  20000 non-null  int64
 11  number_of_reviews               20000 non-null  int64
 12  last_review                     15877 non-null  object
 13  reviews_per_month               15877 non-null  float64
 14  calculated_host_listings_count  20000 non-null  int64
 15  availability_365                20000 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 2.4+ MB

In [42]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,2.000000e+04,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,15877.000000,20000.000000,20000.000000
mean,1.892380e+07,6.746034e+07,40.728455,-73.952125,153.269050,6.992100,23.274100,1.377446,6.955450,112.901200
std,1.101223e+07,7.857936e+07,0.054755,0.046559,243.325609,21.645449,44.927793,1.683006,32.433831,131.762226
min,2.539000e+03,2.571000e+03,40.508730,-74.239140,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.393540e+06,7.853718e+06,40.689420,-73.983030,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.952117e+07,3.111431e+07,40.722730,-73.955640,105.000000,2.000000,5.000000,0.720000,1.000000,44.000000
75%,2.912936e+07,1.068426e+08,40.762990,-73.936380,175.000000,5.000000,23.000000,2.010000,2.000000,229.000000
max,3.648561e+07,2.742733e+08,40.913060,-73.717950,10000.000000,1250.000000,607.000000,27.950000,327.000000,365.000000

In [43]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,9138664,Private Lg Room 15 min to Manhattan,47594947,Iris,Queens,Sunnyside,40.74271,-73.92493,Private room,74,2,6,2019-05-26,0.13,1,5
1,31444015,TIME SQUARE CHARMING ONE BED IN HELL'S KITCHEN...,8523790,Johlex,Manhattan,Hell's Kitchen,40.76682,-73.98878,Entire home/apt,170,3,0,NaN,NaN,1,188
2,8741020,Voted #1 Location Quintessential 1BR W Village...,45854238,John,Manhattan,West Village,40.73631,-74.00611,Entire home/apt,245,3,51,2018-09-19,1.12,1,0
3,34602077,Spacious 1 bedroom apartment 15min from Manhattan,261055465,Regan,Queens,Astoria,40.76424,-73.92351,Entire home/apt,125,3,1,2019-05-24,0.65,1,13
4,23203149,Big beautiful bedroom in huge Bushwick apartment,143460,Megan,Brooklyn,Bushwick,40.69839,-73.92044,Private room,65,2,8,2019-06-23,0.52,2,8

In [44]:
df[df['name'].isna()].head(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
3872,22275821,NaN,49662398,Kathleen,Brooklyn,Bushwick,40.69546,-73.92741,Entire home/apt,110,4,5,2018-08-13,0.27,1,0
4561,6782407,NaN,31147528,Huei-Yin,Brooklyn,Williamsburg,40.71354,-73.93882,Private room,45,1,0,NaN,NaN,1,0
5588,14135050,NaN,85288337,Jeff,Brooklyn,Bedford-Stuyvesant,40.69421,-73.93234,Private room,70,3,0,NaN,NaN,1,0
7259,9885866,NaN,37306329,Juliette,Manhattan,Chinatown,40.71632,-73.99328,Private room,67,4,0,NaN,NaN,1,0
9692,10052289,NaN,49522403,Vanessa,Brooklyn,Brownsville,40.66409,-73.92314,Private room,50,3,3,2016-08-18,0.07,1,362
11666,4581788,NaN,21600904,Lucie,Brooklyn,Williamsburg,40.71370,-73.94378,Private room,150,1,0,NaN,NaN,1,0
14978,12797684,NaN,69715276,Yan,Manhattan,Upper West Side,40.79843,-73.96404,Private room,100,1,0,NaN,NaN,2,0

In [45]:
df[df['host_name'].isna()].head(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
2180,1449546,Cozy Studio in Flatbush,7779204,NaN,Brooklyn,Flatbush,40.64965,-73.96154,Entire home/apt,100,30,49,2017-01-02,0.69,1,342
5268,6992973,1 Bedroom in Prime Williamsburg,5162530,NaN,Brooklyn,Williamsburg,40.71838,-73.95630,Entire home/apt,145,1,0,NaN,NaN,1,0
7059,12113879,"Sunny, Large West Village 1 BR Near Everything",5300585,NaN,Manhattan,Chelsea,40.73949,-73.99801,Entire home/apt,220,4,81,2019-07-02,2.11,1,217
7420,6360224,"Sunny, Private room in Bushwick",33134899,NaN,Brooklyn,Bushwick,40.70146,-73.92792,Private room,37,1,1,2015-07-01,0.02,1,0
11359,23660605,Private Bedroom w/ Balcony view of Central Park,177146433,NaN,Manhattan,East Harlem,40.79766,-73.94824,Private room,139,1,6,2018-08-12,0.46,1,0
17161,6786181,R&S Modern Spacious Hideaway,32722063,NaN,Brooklyn,East Flatbush,40.64345,-73.93643,Entire home/apt,100,2,157,2019-06-19,3.18,2,342
19452,7556587,Sunny Room in Harlem,39608626,NaN,Manhattan,Harlem,40.82929,-73.94182,Private room,28,1,1,2015-08-01,0.02,1,0
19906,21901156,Best Deal! Lovely place in Manhattan! Time Squ...,159156636,NaN,Manhattan,Hell's Kitchen,40.75656,-73.99063,Private room,120,1,109,2019-01-01,5.97,3,0

In [46]:
# Price column summary
df['price'].describe()

count    20000.000000
mean       153.269050
std        243.325609
min          0.000000
25%         69.000000
50%        105.000000
75%        175.000000
max      10000.000000
Name: price, dtype: float64

In [47]:
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['price'] < lower) | (df['price'] > upper)]
print(f"Outliers detected: {len(outliers)} ({len(outliers)/len(df)*100:.2f}%)")
print(f"Upper bound for normal range: {upper:.2f}")

Outliers detected: 1196 (5.98%)
Upper bound for normal range: 334.00

In [48]:
df['last_review'].isna().sum()

np.int64(4123)

In [49]:
df['reviews_per_month'].isna().sum()

np.int64(4123)

In [50]:
(df['last_review'].isna() & df['reviews_per_month'].isna()).sum()

np.int64(4123)

In [51]:
(df['last_review'].isna() == df['reviews_per_month'].isna()).mean()

np.float64(1.0)

In [52]:
if (df['last_review'].isna() == df['reviews_per_month'].isna()).all():
    print("All nulls match")
else:
    print("Nulls do not match")

All nulls match

In [53]:
zero_reviews = df.query('number_of_reviews == 0')
print(f"The number of rows that contains a total count of zero reviews is {len(zero_reviews)}")

The number of rows that contains a total count of zero reviews is 4123

In [54]:
if ((df['number_of_reviews'] == 0) == df['last_review'].isna()).all():
    print("All zero review rows match null last_review items")
else:
    print("zero review rows do not match the same last_review null rows")

All zero review rows match null last_review items

3. What do you notice in the data? Look around and see what you can find.

> For example, there are missing values in a few columns and the column `last_review` is a date but it is in string format. Look also at the `price` column, and note the outliers. There are some zeros and some very high prices. After talking to your stakeholders, you decide to consider from a minimum of `$10` to a maximum of `$350` per night.

In the "number of reviews" column, the rows that have a value of "0" (zero) match the rows that contain a null/nan value in the 'last review' and 'reviews per month' columns. In otherwords, these three columns have a direct correlation to each other.

4. Fix some of the little problems we have found in the data with the following code:

In [55]:
# Drop outliers
min_price = 10
max_price = 350
idx = df['price'].between(min_price, max_price)
df = df[idx].copy()
# Convert last_review to datetime
df['last_review'] = pd.to_datetime(df['last_review'])

Note how we did not impute missing values. We will do that in the inference pipeline, so we will be able to handle missing values also in production.

5. Check with df.info() that all obvious problems have been solved

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19001 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              19001 non-null  int64
 1   name                            18994 non-null  object
 2   host_id                         19001 non-null  int64
 3   host_name                       18993 non-null  object
 4   neighbourhood_group             19001 non-null  object
 5   neighbourhood                   19001 non-null  object
 6   latitude                        19001 non-null  float64
 7   longitude                       19001 non-null  float64
 8   room_type                       19001 non-null  object
 9   price                           19001 non-null  int64
 10  minimum_nights                  19001 non-null  int64
 11  number_of_reviews               19001 non-null  int64
 12  last_review                     15243 non-null  datetime64[ns]
 13  reviews_per_month               15243 non-null  float64
 14  calculated_host_listings_count  19001 non-null  int64
 15  availability_365                19001 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(7), object(5)
memory usage: 2.5+ MB

6. Terminate the run by running `run.finish()`

In [57]:
# Manually log this notebook into weights and biases as an artifact. 

run.log_code(
    ".",
    include_fn=lambda path: path.endswith(".ipynb") or path.endswith(".py")
)

In [58]:
run.finish()

7. Save the notebook.